/**
 * Utilidades compartidas para webhooks de WhatsApp
 *
 * Funciones reutilizadas tanto por el webhook de Evolution API
 * como por el webhook de Meta Cloud API.
 */

import crypto from "crypto"
import { normalizePhone, getPhoneVariants, buildWhatsAppJid } from "@/lib/utils/phone"
import { getMessagingConversationsThisMonth } from "@/lib/utils/whatsapp-limits"

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type SupabaseClient = any

// ============================================
// Customer management
// ============================================

/**
 * Patron que matchea los nombres auto-generados por el fallback de
 * findOrCreateCustomer cuando no llega pushName del webhook:
 *
 *   `WhatsApp ${phoneNumber.slice(-4)}`
 *
 * slice(-4) siempre devuelve exactamente 4 caracteres del remoteJid
 * (digitos, @, ., letras minusculas de sufijos como @lid o @s.whatsapp.net).
 * Si el nombre actual matchea este patron, se considera "auto-generado"
 * y puede ser reemplazado por un pushName real cuando llegue.
 *
 * Caso edge aceptado: un humano nombrado literalmente "WhatsApp 1234"
 * (4 caracteres exactos, solo digitos/letras/@/.) seria sobrescrito.
 * Aceptable porque la probabilidad es minima y el upside (saludar por
 * nombre real) supera al downside (raro nombre sobrescrito).
 */
const AUTO_GENERATED_NAME_PATTERN = /^WhatsApp [\d@.a-z]{4}$/

function isAutoGeneratedName(name: string | null | undefined): boolean {
  if (!name) return true
  return AUTO_GENERATED_NAME_PATTERN.test(name)
}

/**
 * Busca o crea un cliente por número de teléfono.
 * Usa variantes de teléfono para encontrar clientes registrados
 * desde cualquier canal (web, WhatsApp, Instagram, etc.)
 */
export async function findOrCreateCustomer(
  supabase: SupabaseClient,
  organizationId: string,
  phoneNumber: string,
  pushName?: string
) {
  // Buscar cliente existente con variantes de teléfono
  const variants = getPhoneVariants(phoneNumber)
  const canonicalPhone = normalizePhone(phoneNumber)

  const { data: existingCustomers } = await supabase
    .from("customers")
    .select("id, full_name, phone")
    .eq("organization_id", organizationId)
    .in("phone", variants)
    .order("created_at", { ascending: true })
    .limit(1)

  const existing = existingCustomers?.[0]

  if (existing) {
    // Actualizar nombre si llega un pushName real Y el nombre actual esta vacio
    // o es un fallback auto-generado por el sistema ("WhatsApp 3601", "WhatsApp @lid").
    // Asi los customers "atascados" con nombre generico se mejoran cuando WhatsApp
    // empieza a enviar el pushName real (cliente cambia su privacidad, etc.).
    const updates: Record<string, string> = {}
    if (pushName && isAutoGeneratedName(existing.full_name)) {
      updates.full_name = pushName
    }
    // Normalizar el teléfono almacenado al formato canónico
    if (existing.phone !== canonicalPhone) {
      updates.phone = canonicalPhone
    }
    if (Object.keys(updates).length > 0) {
      await supabase
        .from("customers")
        .update(updates)
        .eq("id", existing.id)
    }
    return { ...existing, name: updates.full_name || existing.full_name }
  }

  // Crear nuevo cliente con teléfono normalizado
  const { data: newCustomer, error } = await supabase
    .from("customers")
    .insert({
      organization_id: organizationId,
      phone: canonicalPhone,
      full_name: pushName || `WhatsApp ${phoneNumber.slice(-4)}`,
      metadata: { source: "whatsapp" },
    })
    .select("id, full_name, phone")
    .single()

  if (error) {
    console.error("[WhatsApp Webhook Utils] Error creating customer:", error)
    throw error
  }

  return { ...newCustomer, name: newCustomer.full_name }
}

// ============================================
// Chat management
// ============================================

/**
 * Busca o crea una conversación para el cliente
 * Reutiliza chats activos dentro de ventana de 24 horas
 *
 * @param phoneNumber  Numero limpio (sin sufijo @lid o @s.whatsapp.net), usado
 *                     para matching y como id legible en la UI.
 * @param remoteJid    JID completo original recibido del webhook (ej.
 *                     `123@lid` o `573...@s.whatsapp.net`). Se persiste en
 *                     `chats.whatsapp_jid` y es la fuente de verdad para
 *                     enviar respuestas via Evolution API.
 *
 * Si `remoteJid` es undefined (callers legacy), se reconstruye heuristicamente
 * desde `phoneNumber` via `buildWhatsAppJid` para no perder la columna.
 */
export async function findOrCreateChat(
  supabase: SupabaseClient,
  organizationId: string,
  customerId: string,
  phoneNumber: string,
  remoteJid?: string
) {
  // Buscar chat activo existente (últimas 24 horas)
  const twentyFourHoursAgo = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString()

  const { data: existing } = await supabase
    .from("chats")
    .select("id, whatsapp_jid")
    .eq("organization_id", organizationId)
    .eq("customer_id", customerId)
    .eq("channel", "whatsapp")
    .gte("updated_at", twentyFourHoursAgo)
    .order("updated_at", { ascending: false })
    .limit(1)
    .single()

  if (existing) {
    // Actualizar timestamp; si el chat existente no tiene whatsapp_jid (legacy
    // pre-v1.12.7) y AHORA tenemos uno fresco del webhook, lo poblamos.
    const updates: Record<string, string> = {
      updated_at: new Date().toISOString(),
    }
    if (!existing.whatsapp_jid && remoteJid) {
      updates.whatsapp_jid = remoteJid
    }
    await supabase
      .from("chats")
      .update(updates)
      .eq("id", existing.id)
    return { id: existing.id }
  }

  // Resolver JID a persistir: preferir el original del webhook; si no existe
  // (callers legacy o tests), reconstruir desde phone con heuristica.
  const jidToPersist = remoteJid || buildWhatsAppJid(phoneNumber)

  // Crear nuevo chat
  const { data: newChat, error } = await supabase
    .from("chats")
    .insert({
      organization_id: organizationId,
      customer_id: customerId,
      channel: "whatsapp",
      whatsapp_chat_id: phoneNumber,
      phone_number: phoneNumber,
      whatsapp_jid: jidToPersist,
      status: "active",
    })
    .select("id")
    .single()

  if (error) {
    console.error("[WhatsApp Webhook Utils] Error creating chat:", error)
    throw error
  }

  // Incrementar contador de conversaciones del mes
  await incrementConversationCount(supabase, organizationId)

  return newChat
}

// ============================================
// Conversation limits
// ============================================

const DEFAULT_LIMIT_NO_SUBSCRIPTION = 1000
const DEFAULT_LIMIT_FREE_PLAN = 10

/**
 * Verifica si la organización puede crear más conversaciones
 */
export async function checkConversationLimit(
  supabase: SupabaseClient,
  organizationId: string
): Promise<boolean> {
  // Obtener organización
  const { data: org, error: orgError } = await supabase
    .from("organizations")
    .select("id, whatsapp_conversations_used")
    .eq("id", organizationId)
    .single()

  if (orgError || !org) {
    console.error("[WhatsApp Webhook Utils] Error fetching org:", orgError)
    return false
  }

  // Obtener suscripción activa con plan
  const { data: subscription } = await supabase
    .from("subscriptions")
    .select("id, plan_id, plans(max_whatsapp_conversations)")
    .eq("organization_id", organizationId)
    .eq("status", "active")
    .single()

  let limit: number
  if (subscription?.plans) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const planData = subscription.plans as any
    limit = planData.max_whatsapp_conversations || DEFAULT_LIMIT_FREE_PLAN
  } else {
    limit = DEFAULT_LIMIT_NO_SUBSCRIPTION
  }

  // -1 = ilimitado
  if (limit === -1) return true

  // Conteo dinámico por mes calendario: resetea solo, sin depender del contador
  // acumulativo (whatsapp_conversations_used) ni del cron —cuya falla dejaba
  // tenants bloqueados silenciosamente (incidente recurrente Casa Inmobiliaria).
  const used = await getMessagingConversationsThisMonth(supabase, organizationId)

  console.log(`[WhatsApp Webhook Utils] Conversation limit: used=${used}, limit=${limit}`)

  return used < limit
}

/**
 * Incrementa el contador de conversaciones usadas
 */
export async function incrementConversationCount(
  supabase: SupabaseClient,
  organizationId: string
) {
  await supabase.rpc("increment_whatsapp_conversations", {
    org_id: organizationId,
  })
}

// ============================================
// Webhook logging
// ============================================

/**
 * Guarda un log del webhook recibido para debugging
 */
export async function logWebhook(
  supabase: SupabaseClient,
  webhookType: "whatsapp" | "whatsapp-meta" | "instagram" | "messenger",
  eventType: string,
  instanceName: string | undefined,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  payload: any,
  headers: Record<string, string>
): Promise<void> {
  try {
    await supabase.from("webhook_logs").insert({
      webhook_type: webhookType,
      event_type: eventType,
      instance_name: instanceName,
      payload,
      headers,
      processing_result: "processing",
    })
  } catch (logError) {
    console.error("[WhatsApp Webhook Utils] Failed to log webhook (non-blocking):", logError)
  }
}

/**
 * Actualiza el resultado de procesamiento de un webhook log
 */
export async function updateWebhookLog(
  supabase: SupabaseClient,
  webhookType: string,
  instanceName: string,
  result: "success" | "warning" | "error",
  errorMessage?: string
): Promise<void> {
  try {
    await supabase
      .from("webhook_logs")
      .update({
        processing_result: result,
        error_message: errorMessage || null,
      })
      .eq("instance_name", instanceName)
      .eq("webhook_type", webhookType)
      .order("created_at", { ascending: false })
      .limit(1)
  } catch (logError) {
    console.error("[WhatsApp Webhook Utils] Failed to update webhook log (non-blocking):", logError)
  }
}

// ============================================
// Signature verification
// ============================================

/**
 * Verifica firma HMAC-SHA256 de Meta Cloud API
 * Header: X-Hub-Signature-256: sha256=HASH
 */
export function verifyMetaSignature(
  body: string,
  signature: string | null,
  appSecret: string
): boolean {
  if (!signature) return false

  const hmac = crypto.createHmac("sha256", appSecret)
  hmac.update(body)
  const expectedSignature = `sha256=${hmac.digest("hex")}`

  try {
    return crypto.timingSafeEqual(
      Buffer.from(signature),
      Buffer.from(expectedSignature)
    )
  } catch {
    return false
  }
}

/**
 * Verifica firma de Evolution API webhook
 */
// ============================================
// Social channel customer management (Instagram/Messenger)
// ============================================

/**
 * Busca o crea un cliente por su ID de plataforma social (IGSID o PSID).
 * A diferencia de WhatsApp que usa teléfono, IG y Messenger usan IDs opacos.
 */
export async function findOrCreateCustomerBySocialId(
  supabase: SupabaseClient,
  organizationId: string,
  platform: "instagram" | "messenger",
  platformUserId: string,
  displayName?: string
) {
  const idColumn = platform === "instagram" ? "instagram_id" : "messenger_id"

  // Buscar cliente existente por social ID
  const { data: existing } = await supabase
    .from("customers")
    .select("id, full_name, phone, instagram_id, messenger_id")
    .eq("organization_id", organizationId)
    .eq(idColumn, platformUserId)
    .single()

  if (existing) {
    // Actualizar nombre si tenemos uno nuevo
    if (displayName && !existing.full_name) {
      await supabase
        .from("customers")
        .update({ full_name: displayName })
        .eq("id", existing.id)
    }
    return { ...existing, name: existing.full_name }
  }

  // Crear nuevo cliente
  const { data: newCustomer, error } = await supabase
    .from("customers")
    .insert({
      organization_id: organizationId,
      [idColumn]: platformUserId,
      full_name: displayName || `${platform === "instagram" ? "IG" : "FB"} User ${platformUserId.slice(-4)}`,
      metadata: { source: platform },
    })
    .select("id, full_name, phone, instagram_id, messenger_id")
    .single()

  if (error) {
    console.error(`[Webhook Utils] Error creating ${platform} customer:`, error)
    throw error
  }

  return { ...newCustomer, name: newCustomer.full_name }
}

/**
 * Busca o crea un chat para un canal social (Instagram/Messenger).
 * Usa el social user ID como identificador del chat en vez de teléfono.
 */
export async function findOrCreateSocialChat(
  supabase: SupabaseClient,
  organizationId: string,
  customerId: string,
  platform: "instagram" | "messenger",
  platformUserId: string
) {
  // Buscar chat activo existente (últimas 24 horas)
  const twentyFourHoursAgo = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString()

  const { data: existing } = await supabase
    .from("chats")
    .select("id")
    .eq("organization_id", organizationId)
    .eq("customer_id", customerId)
    .eq("channel", platform)
    .gte("updated_at", twentyFourHoursAgo)
    .order("updated_at", { ascending: false })
    .limit(1)
    .single()

  if (existing) {
    await supabase
      .from("chats")
      .update({ updated_at: new Date().toISOString() })
      .eq("id", existing.id)
    return existing
  }

  // Crear nuevo chat
  const { data: newChat, error } = await supabase
    .from("chats")
    .insert({
      organization_id: organizationId,
      customer_id: customerId,
      channel: platform,
      // Guardar social user ID en whatsapp_chat_id (campo genérico para ID externo)
      whatsapp_chat_id: platformUserId,
      status: "active",
      metadata: { platform_user_id: platformUserId },
    })
    .select("id")
    .single()

  if (error) {
    console.error(`[Webhook Utils] Error creating ${platform} chat:`, error)
    throw error
  }

  // Incrementar contador de conversaciones
  await incrementConversationCount(supabase, organizationId)

  return newChat
}

export function verifyEvolutionSignature(
  body: string,
  signature: string | null,
  webhookSecret: string
): boolean {
  if (!signature) return false

  const hmac = crypto.createHmac("sha256", webhookSecret)
  hmac.update(body)
  const expectedSignature = `sha256=${hmac.digest("hex")}`

  try {
    return crypto.timingSafeEqual(
      Buffer.from(signature),
      Buffer.from(expectedSignature)
    )
  } catch {
    return false
  }
}
